#pragma once

#include <vector>
#include <sstream>
#include <string>
#include <iostream>
#include <vamplogger/logger.h>
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include "layer.h"
#include "application.h"
#include "window.h"
#include "shader.h"
#include "texture.h"
#include "../debug/glcall.h"
#include "../systems/camera.h"
#include "mesh.h"